package com.volvo.assistanceandroid

enum class Action(val label: Int, val answer: String) {
    MACHINE_FRONT_WORKLIGHT_ON(0, "Yes, I'll turn on the front work light"),
    MACHINE_FRONT_WORKLIGHT_OFF(1, "Yes, I'll turn off the front work light"),
    MACHINE_BOOM_WORKLIGHT_ON(2, "Yes, I'll turn on the boom work light"),
    MACHINE_BOOM_WORKLIGHT_OFF(3, "Yes, I'll turn ff the boom work light"),
    MACHINE_SIDE_WORKLIGHT_ON(4, "Yes, I'll turn on the side work light"),
    MACHINE_SIDE_WORKLIGHT_OFF(5, "Yes, I'll turn off the side work light"),
    MACHINE_REAR_WORKLIGHT_ON(6, "Yes, I'll turn on the rear work light"),
    MACHINE_REAR_WORKLIGHT_OFF(7, "Yes, I'll turn on the rear work light"),
    MACHINE_WORKMODE_ECO(8, "Yes, I will change to eco work mode"),
    MACHINE_WORKMODE_POWER(9, "Yes, I will change to power work mode"),
    MACHINE_WORKMODE_LIFTING(10, "Yes, I will change to lifting work mode"),
    MACHINE_WIPER_ON(11, "Yes, I'll get your wipers running"),
    MACHINE_WIPER_OFF(12, "Yes, I'll disable your wipers running"),
    MACHINE_LEVEL_STATUS(13, ""),
    MACHINE_SERVICE_STATUS(14, ""),
    MACHINE_OPERATING_INFO_STATUS(15, ""),
    CLIMATE_TEMPERATURE_UP(16, ""),
    CLIMATE_TEMPERATURE_DOWN(17, ""),
    CLIMATE_MODE_AUTO(18, ""),
    CLIMATE_MODE_MANUAL(19, ""),
    MEDIA_MUSIC_ON(20, ""),
    MEDIA_MUSIC_OFF(21, ""),
    MEDIA_RADIO_ON(22, ""),
    MEDIA_RADIO_OFF(23, ""),
    NONE(100, "I don't understand well. could you say it again?"),
}